apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-pd-balanced
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-balanced
