apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-2022
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-sqlserver-2022
  template:
    metadata:
      labels:
        app: ms-sqlserver-2022
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 10001      
      containers:
        - name: ms-sqlserver-2022
          image: mcr.microsoft.com/mssql/server:2022-latest
          resources:
            requests:
              memory: "2G"
              cpu: "2000m"
            limits:
              memory: "2G"
              cpu: "2000m"          
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-2022-secret
                  key: SA_PASSWORD
          volumeMounts:
            - name: sql-server-volume
              mountPath: /var/opt/mssql
      volumes:
        - name: sql-server-volume
          persistentVolumeClaim:
            claimName: sql-server-2022-pvc